# [original] local: <path>/backgrounds.conf
<backgrounds>

# Show the backgrounds only for ideograms that have data
show  = data

<background>
color = vvlgrey
</background>

<background>
color = vvlgrey
</background>

</backgrounds>