# [original] local: <path>/KP.circos.conf
# Circos Main Configuration File

karyotype = karyotype.txt

chromosomes_units = 1000000
chromosomes_display_default = no
chromosomes= SUPER_1;SUPER_2;SUPER_3;SUPER_4;SUPER_5;SUPER_6;SUPER_7;SUPER_8;SUPER_9;SUPER_10;SUPER_11;SUPER_12;SUPER_13;SUPER_14;SUPER_15;SUPER_16;SUPER_17;SUPER_18;SUPER_19;SUPER_20;SUPER_21;SUPER_22;SUPER_23;SUPER_24;SUPER_25;SUPER_26;SUPER_27;SUPER_28;SUPER_29;SUPER_30;SUPER_31;SUPER_32;SUPER_Z;SUPER_W
chromosomes_order = SUPER_1,SUPER_2,SUPER_3,SUPER_4,SUPER_5,SUPER_6,SUPER_7,SUPER_8,SUPER_9,SUPER_10,SUPER_11,SUPER_12,SUPER_13,SUPER_14,SUPER_15,SUPER_16,SUPER_17,SUPER_18,SUPER_19,SUPER_20,SUPER_21,SUPER_22,SUPER_23,SUPER_24,SUPER_25,SUPER_26,SUPER_27,SUPER_28,SUPER_29,SUPER_30,SUPER_31,SUPER_32,SUPER_Z,SUPER_W


# Define the appearance of the ideogram
#ideogram configuration
<ideogram>

 <spacing> 
  # spacing between ideograms is 0.1% of image
  default = 0.010r 

  <pairwise SUPER_W SUPER_1>
   # spacing between hsY and hs1 is 50x 0.1% of image
   spacing = 2r 
  </pairwise>

 </spacing>

#<spacing>
#default = 0.005r
#</spacing>
 
# Ideogram position; fill and outline
 
radius           = 0.90r
thickness        = 30p
fill             = yes
stroke_color     = black
stroke_thickness = 4p
 
# Minimum definition for ideogram labels.
 
show_label       = yes
# see etc/fonts.conf for list of font names
label_font       = default
label_radius     = 1r + 75p
label_size       = 30
label_parallel   = yes
 
</ideogram>

# Define the plots (tracks)
<plots>
#        r1 = 0.95r
#        r0 = 0.85r
### GC plot
<<include backgrounds.conf>>

#      <plot>
#         type = line
#         file = gc_content_50kb.circos.txt
#         r1 = 0.95r
#         r0 = 0.85r
#         color = black
# 	thickness = 3
# 	stroke_thickness = 8
# 	stroke_color = black
# 	extend_bin = yes
# 	smoothing = 5
#     </plot>

# ### methylation content plot
#      <plot>
#          type = line
#          file = methylation_content_50kb.circos.txt
#          r1 = 0.80r
#          r0 = 0.70r
#          color = blue
# 	 thickness = 2
# 	 smoothing = 5
#  #        min = 0
#  #        max = 0.8
#  #	scale_log_base = 3
#      </plot>

### Gene content plot
<plot>
    	type = heatmap
	file = gene_content_200kb.circos.txt
    	r1 = 0.65r
    	r0 = 0.55r
#    	color = ylgrbu-13
	color = purd-13
	min = 0
	max = 0.8
#	extend_bin=yes
#	skip_run = yes
#	thickness = 4p
    </plot>

### Repeat content plot
 #     <plot>
 #         type = heatmap
 #         file = repeat_content_50kb.circos.txt
 #         r1 = 0.50r
 #         r0 = 0.40r
 #         color = ylorrd-13
 #         min = 0
 #         max = 0.8
 # #	scale_log_base = 3
 #     </plot>

</plots>


# Image configuration
<image>
    radius = 1500p
    background = white
    dir = .
    file = circos.png
    png = yes
    svg = yes
</image>

# General settings
<<include etc/colors_fonts_patterns.conf>>
<<include etc/housekeeping.conf>>
<<include ticks.conf>>

<image>
<<include etc/image.conf>>
# now override as necessary
auto_alpha_colors*           = yes
auto_alpha_steps* = 10
angle_offset* = -87
</image>

