# [original] local: <path>/backgrounds.conf
<backgrounds>
# Show the backgrounds only for ideograms that have data
show  = data

#<background>
#color = lowexp
#</background>

<background>
color = vlowexp
y0    = 0r
y1    = 0.5r
</background>

<background>
color = highexp
y0    = 0.5r
y1    = 1r
</background>

#<background>
#color = vhighexp
#y0    = 0.8r
#</background>

</backgrounds>