# [original] local: <path>/gene_exp.circos.conf
# Circos Main Configuration File

karyotype = karyotype.txt

chromosomes_units = 1000000
chromosomes_display_default = yes
#chromosomes= SUPER_1;SUPER_2;SUPER_3;SUPER_4;SUPER_5;SUPER_6;SUPER_7;SUPER_8;SUPER_9;SUPER_10;SUPER_11;SUPER_12;SUPER_13;SUPER_14;SUPER_15;SUPER_16;SUPER_17;SUPER_18;SUPER_19;SUPER_20;SUPER_21;SUPER_22;SUPER_23;SUPER_24;SUPER_25;SUPER_26;SUPER_27;SUPER_28;SUPER_29;SUPER_30;SUPER_31;SUPER_32;SUPER_Z;SUPER_W
#chromosomes_order = SUPER_1,SUPER_2,SUPER_3,SUPER_4,SUPER_5,SUPER_6,SUPER_7,SUPER_8,SUPER_9,SUPER_10,SUPER_11,SUPER_12,SUPER_13,SUPER_14,SUPER_15,SUPER_16,SUPER_17,SUPER_18,SUPER_19,SUPER_20,SUPER_21,SUPER_22,SUPER_23,SUPER_24,SUPER_25,SUPER_26,SUPER_27,SUPER_28,SUPER_29,SUPER_30,SUPER_31,SUPER_32,SUPER_Z,SUPER_Define


# the appearance of the ideogram
#ideogram configuration
<ideogram>

 <spacing> 
  default = 0.005r 

 </spacing>

# Ideogram position; fill and outline
 
radius           = 0.90r
thickness        = 40p
fill             = yes
stroke_color     = black
stroke_thickness = 4p
 
# Minimum definition for ideogram labels.
 
show_label       = yes
# see etc/fonts.conf for list of font names
label_font       = default
label_radius     = 1r + 75p
label_size       = 30
label_parallel   = yes
 
</ideogram>

# Define the plots (tracks)
<plots>

<<include backgrounds.conf>>

# ### Brain expression plot
     <plot>
         type = histogram
         file = brain_sig0.05.fc5.txt
         r1 = 0.95r
         r0 = 0.85r
	 thickness = 5
         color = brain
	 extend_bin = no
	 skip_run = yes
	 min = -20
	 max = 20
 #	scale_log_base = 3
     </plot>


### Kidney expression plot
     <plot>
         type = histogram
         file = kidney_sig0.05.fc5.txt
         r1 = 0.80r
         r0 = 0.70r
 	 thickness = 5
         color = kidney
	 extend_bin = no
	 skip_run = yes
	 min = -20
	 max = 20
 #	scale_log_base = 3
     </plot>


### Liver expression plot
     <plot>
         type = histogram
         file = liver_sig0.05.fc5.txt
         r1 = 0.65r
         r0 = 0.55r
	 thickness = 5
	 color = liver
	 extend_bin = no
	 skip_run = yes	 
 #	scale_log_base = 3
     </plot>

### Muscle expression plot
     <plot>
         type = histogram
         file = muscle_sig0.05.fc5.txt
         r1 = 0.50r
         r0 = 0.40r
	 thickness = 5
	 color = muscle
	 extend_bin = no
	 skip_run = yes
	 min = -20
	 max = 20
 #	scale_log_base = 3
     </plot>

### Skin expression plot
     <plot>
         type = histogram
         file = skin_sig0.05.fc5.txt
         r1 = 0.35r
         r0 = 0.25r
	 thickness = 5
         color = skin
	 extend_bin = no
	 skip_run = yes
	 min = -20
	 max = 20
 #	scale_log_base = 3
     </plot>

</plots>


# Image configuration
<image>
    radius = 1500p
    background = white
    dir = .
    file = circos.png
    png = yes
    svg = yes
</image>

# General settings
<<include etc/colors_fonts_patterns.conf>>
<<include etc/housekeeping.conf>>
<<include ticks.conf>>

<image>
<<include etc/image.conf>>
# now override as necessary
auto_alpha_colors*           = yes
auto_alpha_steps* = 30
angle_offset* = -85
</image>

